parameters:
    indigo_game.game_finish_listener.class: Indigo\GameBundle\EventListener\GameFinishListener
    game.rating_calculator.class: Indigo\GameBundle\Service\RatingService
services:
    game.finish.listener:
      class: %indigo_game.game_finish_listener.class%
      arguments: ["@doctrine.orm.entity_manager"]
      tags:
          - { name: kernel.event_listener, event: indigo_game.finish_on_double_swipe, method: onGameFinishDoubleSwipe }
          - { name: kernel.event_listener, event: indigo_game.finish_on_score, method: onGameFinishMaxScoreReached }
#          - { name: kernel.event_listener, event: indigo_game.calculate_ratings, method: onRatingsCalculate }
#   indigo_game.example:
#        class: Indigo\GameBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


    indigo_game.rating:
      class: %game.rating_calculator.class%
      arguments: ["@doctrine.orm.entity_manager"]


    indigo_game.rating.subscriber:
        class: Indigo\GameBundle\EventListener\RatingCalculatorSubscriber
        calls:
            - [ setRatingService, ["@indigo_game.rating"] ]
        tags:
            - { name: kernel.event_subscriber }
