indigo_ui_homepage:
    path:     /hello/{name}
    defaults: { _controller: IndigoUIBundle:Default:index }


indigo_ui_live:
    path:     /live/
    defaults: { _controller: IndigoUIBundle:Live:live }

indigo_ui_dashboard:
    path:     /dashboard/
    defaults: { _controller: IndigoUIBundle:Dashboard:dashboard }

indigo_ui_table_status:
        path:     /live/status/
        defaults: { _controller: IndigoUIBundle:Live:status }
        requirements:
                _method: POST|GET