indigo_ui_live:
    path:     /live/{id}
    defaults: { _controller: IndigoUIBundle:Live:live, id:0 }


indigo_ui_live_widget:
    path:     /live/widget/{id}
    defaults: { _controller: IndigoUIBundle:Live:widget, id:0 }

indigo_ui_table_status:
        path:     /live/status/{id}
        defaults: { _controller: IndigoUIBundle:Live:status, id:0 }
        requirements:
                _method: POST|GET

indigo_ui_dashboard:
    path:     /dashboard/{id}
    defaults: { _controller: IndigoUIBundle:Dashboard:dashboard, id:1 }
    requirements:
            _method: GET

indigo_ui_get_contest_list:
    path:     /dashboard/contest/list{id}
    defaults: { _controller: IndigoUIBundle:Dashboard:dashboard, id:1 }
    requirements:
            _method: GET