parameters:
    indigo_ui.live_view_service.class: Indigo\UIBundle\Services\LiveViewService
    indigo_ui.dashboard_view_service.class: Indigo\UIBundle\Services\DashboardViewService

    indigo_ui.player_stat.service.class: Indigo\UIBundle\Services\PlayerStatService
    indigo_ui.contest_stat.service.class: Indigo\UIBundle\Services\ContestStatService
    indigo_ui.game_history.service.class: Indigo\UIBundle\Services\GameHistoryViewService

services:
    indigo_ui.live_view_service:
      class: %indigo_ui.live_view_service.class%
      arguments: ["@doctrine.orm.entity_manager"]


    indigo_ui.dashboard_view_service:
      class: %indigo_ui.dashboard_view_service.class%
      arguments: ["@doctrine.orm.entity_manager","@indigo_ui.player_stat.service", "@indigo_ui.contest_stat.service"]

    indigo_ui.player_stat.service:
      class: %indigo_ui.player_stat.service.class%
      arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]
      calls:
          - [setLogger, ["@?logger"]]
      tags:
        - { name: monolog.logger, channel: ui.dashboard_stats }

    indigo_ui.contest_stat.service:
      class: %indigo_ui.contest_stat.service.class%
      arguments: ["@doctrine.orm.entity_manager"]
      calls:
          - [setLogger, ["@?logger"]]
      tags:
        - { name: monolog.logger, channel: ui.dashboard_stats }

    indigo_ui.game_history.service:
      class: %indigo_ui.game_history.service.class%
      arguments: ["@doctrine.orm.entity_manager"]
      calls:
          - [setLogger, ["@?logger"]]
      tags:
        - { name: monolog.logger, channel: ui.dashboard_stats }