indigo_contest:
    resource: "@IndigoContestBundle/Controller/"
    type:     annotation
    prefix:   /

indigo_locations_reg:
    resource: "@IndigoLocationsRegBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
