testing:
    resource: "@TestingBundle/Controller/"
    type:     annotation
    prefix:   /

indigo_user:
    resource: "@IndigoUserBundle/Controller/"
    type:     annotation
    prefix:   /
    
indigo_contest:
    resource: "@IndigoContestBundle/Controller/"
    type:     annotation
    prefix:   /

indigo_locations_reg:
    resource: "@IndigoLocationsRegBundle/Controller/"
    type:     annotation
    prefix:   /
