<?php

namespace Indigo\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RemindPasswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResetPasswordRepository extends EntityRepository
{
}
