<?php

namespace Indigo\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * SignInRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getUser($email, $password)
    {
        $qb = $this->_em->createQueryBuilder();
        //createQuery("SELECT `id` FROM IndigoUserBundle:User WHERE `email`=")
        $qb
            ->select('u.id')
            ->from('IndigoUserBundle:User','u')
            ->where("u.email= :email")
            ->andWhere("u.password = :password")
            ->setParameters([
                    'email' => $email,
                    'password' => md5($password)
            ]);


        $query = $qb->getQuery();

        return $query->getArrayResult();
    }


    /**
     * @return array
     */
    public function userExists($email)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb
            ->select('u.id')
            ->from('IndigoUserBundle:User','u')
            ->where("u.email= :email")
            ->setParameter('email', $email );
        $query = $qb->getQuery();

        return $query->getArrayResult();
    }
}
