indigo_main_homepage:
    path:     /{name}
    defaults: { _controller: IndigoMainBundle:Default:index }

indigo_main_homepage:
    path:     /
    defaults: { _controller: IndigoMainBundle:Default:index }