#!/usr/bin/env php
<?


require dirname(__DIR__) . '/vendor/autoload.php';

use Symfony\Component\Console\Application as ConsoleApplication;
use Indigo\API\Command\EventCapture;

$app = new ConsoleApplication('Table API', 'v0.1');

$app->add(new \Indigo\API\Command\EventCaptureCommand());
$app->run(new Symfony\Component\Console\Input\ArgvInput(), new Symfony\Component\Console\Output\ConsoleOutput());
