<?php

namespace Indigo\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameTimeRepository extends EntityRepository
{
}
