<?php

namespace Indigo\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Acl\Exception\Exception;


/**
 * GameTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameTimeRepository extends EntityRepository
{

    CONST GAMETIME_TOLERANCE = 18000;

    /**
     * @param \ArrayIterator $players
     * @return null
     */
    public function getEarliestReservation(\ArrayIterator $players)
    {

        //$meta = $em->getClassMetadata(get_class($entity));
        //$identifier = $meta->getSingleIdentifierFieldName();
        try {
            $playersIdArray = [];
            foreach ($players as $playerId) {
                $meta = $this->_em->getClassMetadata(get_class($playerId));
                $identifier = $meta->getIdentifierValues($playerId);
                $playersIdArray [] = $identifier;
            }
            $qb = $this->_em->createQuery("
                SELECT gt
                FROM Indigo\GameBundle\Entity\GameTime gt
                WHERE
                gt.timeOwner IN ( :players )
                    AND gt.confirmed = '0'
                    AND (ABS( TIME_TO_SEC( TIMEDIFF(gt.startAt, CURRENT_TIMESTAMP())) ) <= :timeInSec
                    OR (gt.startAt <= CURRENT_TIMESTAMP() AND gt.finishAt >= CURRENT_TIMESTAMP()))
                ORDER BY gt.startAt ASC
                ")
                ->setParameters([
                    'players'=> $playersIdArray,
                    'timeInSec' => self::GAMETIME_TOLERANCE
                ]);

            //var_dump ($qb->getSQL());
            //var_dump ($qb->getParameters());
            $reservation = $qb->getSingleResult();
        } catch (\Exception $e) {

            return  null;
        }
        return $reservation;
    }

}
