<?php

namespace Indigo\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RemindPasswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{

<<<<<<< HEAD
=======

>>>>>>> api_test
}
