<?php

namespace Indigo\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TableStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableStatusRepository extends EntityRepository
{
}
