encoders:
        Indigo\UserBundle\Entity\User:
            class: Symfony\Component\Security\Core\Encoder\MessageDigestPasswordEncoder
            algorithm:        md5
            encode_as_base64: false
            iterations:       1