parameters:
        indigo_user.registration.service.class: Indigo\UserBundle\Service\Registration
services:
    indigo_user.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Indigo\UserBundle\Entity\User

    indigo_role.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Indigo\UserBundle\Entity\Role

    indigo_reset_password.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Indigo\UserBundle\Entity\ResetPassword


    indigo_user.registration.service:
            class: %indigo_user.registration.service.class%
            arguments: ["@doctrine.orm.entity_manager", "@security.encoder_factory"]